Update to intellij 2024.2+
EnzDev/idea-ngx-translate-autocomplete pull request #217
Opened 2024-11-29 15:27 UTC by Minecraftschurli

2024-12-04 16:56 UTC, EnzDev requested changes
Thanks for your help ! It seems your merge request needs some small changes for the CI to pass, I'll need it to deploy the plugin 😉

2024-12-04 16:56 UTC, EnzDev commented on .github/workflows/build.yml
Hello, there is some small parts that needs changes from what I'm seeing in the [IntelliJ template repository](https://github.com/JetBrains/intellij-platform-plugin-template/blob/main/.github/workflows/build.yml).

`Export Properties` job should not execute `./gradlew listProductsReleases # prepare list of IDEs for Plugin Verifier` anymore.
![export properties](https://github.com/user-attachments/assets/4bc1720d-45ce-470f-b25a-0a42b71fd782)

[Sources should be fetched with full history before running Qodana](https://github.com/JetBrains/intellij-platform-plugin-template/commit/e6049b22835567f429a45d4dce4881c1728bcd84)
![fetch pr](https://github.com/user-attachments/assets/3b9da5c9-96a2-4d2a-ac88-adb28132b033)

Plugin verifier command has changed
![plugin verifier](https://github.com/user-attachments/assets/3e1d0831-ef7f-4459-8691-2383f3d74507)

2024-12-04 16:58 UTC, EnzDev commented
If you prefer it is also possible for me to add you as a contributor so you can create a branch with your changes so we can collaborate

2024-12-04 20:50 UTC, EnzDev commented
I'll merge to next to allow me to do the final CI fixes :) Thanks !

2024-12-04 20:50 UTC, merged

2024-12-04 20:52 UTC, Minecraftschurli commented
Oh I was working on the fix for the verify task

2024-12-05 11:24 UTC, EnzDev commented
> Oh I was working on the fix for the verify task
Really sorry for that, I wasn't sure the CI was working automatically for you because I had to validate to run them.
Thanks a lot again for your help :)